### PR TITLE
Set `enable-experimental-jit=yes-off` on Python 3.13 / Linux

### PR DESCRIPTION
**Pull request by zanieb**
See #535 

This builds the JIT, but disables it by default. Users can opt-in to enable it at runtime.

3.14 and macOS support will follow, there are some hiccups there.

### CODE REVIEW

**Comment by zanieb** [comment]
[x86_64-apple-darwin / 3.14 / freethreaded+pgo+lto](https://github.com/astral-sh/python-build-standalone/actions/runs/13512150518/job/37754641848?pr=538#logs)

```
cpython-3.14> In file included from Python/ceval.c:781:
cpython-3.14> Python/generated_cases.c.h:4934:13: error: use of undeclared label 'error'
cpython-3.14>  4934 |             GOTO_TIER_TWO(executor);
cpython-3.14>       |             ^
cpython-3.14> Python/ceval_macros.h:398:14: note: expanded from macro 'GOTO_TIER_TWO'
cpython-3.14>   398 |         goto error;                                    \
cpython-3.14>       |              ^
cpython-3.14> In file included from Python/ceval.c:781:
cpython-3.14> Python/generated_cases.c.h:6968:25: error: use of undeclared label 'error'
cpython-3.14>  6968 |                         GOTO_TIER_TWO(executor);
cpython-3.14>       |                         ^
cpython-3.14> Python/ceval_macros.h:398:14: note: expanded from macro 'GOTO_TIER_TWO'
cpython-3.14>   398 |         goto error;                                    \
cpython-3.14>       |              ^
cpython-3.14> 2 errors generated.
```

**Comment by zanieb** [comment]
[aarch64-apple-darwin / 3.13 / freethreaded+pgo+lto](https://github.com/astral-sh/python-build-standalone/actions/runs/13512150518/job/37754639630?pr=538#logs)

```
cpython-3.13> 
cpython-3.13> ===========================================================
cpython-3.13> JIT support for aarch64-apple-darwin is still experimental!
cpython-3.13>           Please report any issues you encounter.
cpython-3.13> ===========================================================
cpython-3.13> 
cpython-3.13>   + Exception Group Traceback (most recent call last):
cpython-3.13>   |   File "/private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmp9dae5lu8/Python-3.13.2/./Tools/jit/build.py", line 28, in <module>
cpython-3.13>   |     args.target.build(pathlib.Path.cwd(), comment=comment, force=args.force)
cpython-3.13>   |     ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cpython-3.13>   |   File "/private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmp9dae5lu8/Python-3.13.2/Tools/jit/_targets.py", line 214, in build
cpython-3.13>   |     stencil_groups = asyncio.run(self._build_stencils())
cpython-3.13>   |   File "/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmp9dae5lu8/tools/host/lib/python3.13/asyncio/runners.py", line 195, in run
cpython-3.13>   |     return runner.run(main)
cpython-3.13>   |            ~~~~~~~~~~^^^^^^
cpython-3.13>   |   File "/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmp9dae5lu8/tools/host/lib/python3.13/asyncio/runners.py", line 118, in run
cpython-3.13>   |     return self._loop.run_until_complete(task)
cpython-3.13>   |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
cpython-3.13>   |   File "/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmp9dae5lu8/tools/host/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
cpython-3.13>   |     return future.result()
cpython-3.13>   |            ~~~~~~~~~~~~~^^
cpython-3.13>   |   File "/private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmp9dae5lu8/Python-3.13.2/Tools/jit/_targets.py", line 189, in _build_stencils
cpython-3.13>   |     async with asyncio.TaskGroup() as group:
cpython-3.13>   |                ~~~~~~~~~~~~~~~~~^^
cpython-3.13>   |   File "/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmp9dae5lu8/tools/host/lib/python3.13/asyncio/taskgroups.py", line 71, in __aexit__
cpython-3.13>   |     return await self._aexit(et, exc)
cpython-3.13>   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
cpython-3.13>   |   File "/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmp9dae5lu8/tools/host/lib/python3.13/asyncio/taskgroups.py", line 173, in _aexit
cpython-3.13>   |     raise BaseExceptionGroup(
cpython-3.13>   |     ...<2 lines>...
cpython-3.13>   |     ) from None
cpython-3.13>   | ExceptionGroup: unhandled errors in a TaskGroup (2 sub-exceptions)
cpython-3.13>   +-+---------------- 1 ----------------
cpython-3.13>     | Traceback (most recent call last):
cpython-3.13>     |   File "/private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmp9dae5lu8/Python-3.13.2/Tools/jit/_targets.py", line 180, in _compile
cpython-3.13>     |     await _llvm.run("clang", args_o, echo=self.verbose)
cpython-3.13>     |   File "/private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmp9dae5lu8/Python-3.13.2/Tools/jit/_llvm.py", line 99, in run
cpython-3.13>     |     raise RuntimeError(f"Can't find {tool}-{_LLVM_VERSION}!")
cpython-3.13>     | RuntimeError: Can't find clang-18!
cpython-3.13>     +---------------- 2 ----------------
cpython-3.13>     | Traceback (most recent call last):
cpython-3.13>     |   File "/private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmp9dae5lu8/Python-3.13.2/Tools/jit/_targets.py", line 180, in _compile
cpython-3.13>     |     await _llvm.run("clang", args_o, echo=self.verbose)
cpython-3.13>     |   File "/private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmp9dae5lu8/Python-3.13.2/Tools/jit/_llvm.py", line 99, in run
cpython-3.13>     |     raise RuntimeError(f"Can't find {tool}-{_LLVM_VERSION}!")
cpython-3.13>     | RuntimeError: Can't find clang-18!
cpython-3.13>     +------------------------------------
cpython-3.13> make[2]: *** [jit_stencils.h] Error 1
```

**Comment by zanieb** [comment]
Looks like 3.13 fails missing Clang 18 and 3.14 fails due to use of undeclared label.

**Comment by brandtbucher** [comment]
Thanks! To clarify, these are free-threading + JIT?

**Comment by brandtbucher** [comment]
I assume you can't use Clang 18 to build it on 3.13? As a quick hack, replacing `_LLVM_VERSION = 18` with `_LLVM_VERSION = 19` at the top of `Tools/jit/_llvm.py` will probably work. (We could maybe also backport a change to accept both versions if needed.)

**Comment by zanieb** [comment]
All the failures I linked happened to be the free-threaded builds, but you can see non-freethreaded failures too. 

- [x86_64_v3-unknown-linux-gnu / 3.14 / pgo+lto](https://github.com/astral-sh/python-build-standalone/actions/runs/13512150513/job/37754343692?pr=538#logs)
- [x86_64_v2-unknown-linux-gnu / 3.13 / pgo+lto](https://github.com/astral-sh/python-build-standalone/actions/runs/13512150513/job/37754341773?pr=538#logs)

I started copying failures then realized all of the relevant builds had failed.

> I assume you can't use Clang 18 to build it on 3.13? 

I think it'd be a pain to have a separate toolchain for it, yeah.

> As a quick hack, replacing _LLVM_VERSION = 18 with _LLVM_VERSION = 19 at the top of Tools/jit/_llvm.py will probably work. 

I'll try that. Thanks!

**Comment by zanieb** [comment]
That got us to a new failure on macOS, e.g.,

[aarch64-apple-darwin / 3.13 / pgo+lto](https://github.com/astral-sh/python-build-standalone/actions/runs/13551453357/job/37875842482?pr=538#logs)
[x86_64-apple-darwin / 3.13 / pgo+lto](https://github.com/astral-sh/python-build-standalone/actions/runs/13551453357/job/37875844107?pr=538#logs)

```
cpython-3.13> In file included from /private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmpb39azrd3/Python-3.13.2/Tools/jit/template.c:1:
cpython-3.13> /private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmpb39azrd3/Python-3.13.2/Include/Python.h:19:10: fatal error: 'assert.h' file not found
cpython-3.13>    19 | #include <assert.h>               // assert()
cpython-3.13>       |          ^~~~~~~~~~
cpython-3.13> In file included from /private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmpb39azrd3/Python-3.13.2/Tools/jit/template.c:1:
cpython-3.13> /private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmpb39azrd3/Python-3.13.2/Include/Python.h:19:10: fatal error: 'assert.h' file not found
cpython-3.13>    19 | #include <assert.h>               // assert()
cpython-3.13>       |          ^~~~~~~~~~
cpython-3.13> In file included from /private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmpb39azrd3/Python-3.13.2/Tools/jit/template.c:1:
cpython-3.13> /private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmpb39azrd3/Python-3.13.2/Include/Python.h:19:10: fatal error: 'assert.h' file not found
cpython-3.13>    19 | #include <asserIn file included from In file included from /private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmpb39azrd3/Python-3.13.2/Tools/jit/template.c:1:
cpython-3.13> /private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmpb39azrd3/Python-3.13.2/Include/Python.h:t19.:10: h>fatal error: 'assert.h' file not found
cpython-3.13>        19 | #include <assert.h>               // assert()
cpython-3.13>       |          ^~~~~~~~~~
cpython-3.13>            // assert()
cpython-3.13>       |          ^~~~~~~~~~
cpython-3.13> In file included from /private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmpb39azrd3/Python-3.13.2/Tools/jit/template.c:1:
cpython-3.13> /private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmpb39azrd3/Python-3.13.2/Include/Python.h:19:10: fatal error: 'assert.h' file not found
cpython-3.13>    19 | #include <assert.h>               // assert()
cpython-3.13>       |          ^~~~~~~~~~
cpython-3.13> /private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmpb39azrd3/Python-3.13.2/Tools/jit/template.c:1:
cpython-3.13> /private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmpb39azrd3/Python-3.13.2/Include/Python.h:19:10: fatal error: 'assert.h' file not found
cpython-3.13>    19 | #include <assert.h>               // assert()
cpython-3.13>       |          ^~~~~~~~~~
cpython-3.13> In file included from /private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmpb39azrd3/Python-3.13.2/Tools/jit/template.c:1:
cpython-3.13> /private/var/folders/y4/8dcllrc96x32z0w3fgrlx6_m0000gn/T/tmpb39azrd3/Python-3.13.2/Include/Python.h:19:10: fatal error: 'assert.h' file not found
cpython-3.13>    19 | #include <assert.h>               // assert()
cpython-3.13>       |          ^~~~~~~~~~
```

**Comment by zanieb** [comment]
But hey the 3.13 Linux jobs pass now!

**Comment by zanieb** [comment]
I'd like to merge this so I'm going to turn the jit off on 3.14 and macOS — we can revisit those later.

**Comment by brandtbucher** [comment]
Weird. Are you using apple clang, or a separate LLVM install? It should be the latter.

The JIT files are compiled separately from the main build system. If you're modifying search paths in any way, you might have to add similar compiler options here: https://github.com/python/cpython/blob/fda056e64bdfcac3dd3d13eebda0a24994d83cb8/Tools/jit/_targets.py#L108-L144

Or, if they're target-specific, you can add them to the `args` keyword passed to the target when we construct it here: https://github.com/python/cpython/blob/fda056e64bdfcac3dd3d13eebda0a24994d83cb8/Tools/jit/_targets.py#L499-L526

**Comment by brandtbucher** [comment]
For the missing label, what tags are you building here? Want to see if I can reproduce.

**Comment by brandtbucher** [comment]
Oh, it looks like you're also building the tail-calling interpreter too? That's likely the problem. You'll want to patch in https://github.com/python/cpython/pull/129820/files#diff-45baf725df91ed7826458cda8a17c2b4a2e5296504de1ed6a1c5a9ebe6390a47, where that was fixed. The JIT and tail-calling didn't work together before that.

**Comment by brandtbucher** [comment]
(But thanks for stress-testing us with your bleeding-edge free-threaded tail-calling JIT builds, haha.)

**Comment by zanieb** [comment]
Tested on Linux

```
❯ ./python/install/bin/python3 loops.py
3.13.2 (main, Feb 26 2025, 23:10:54) [Clang 19.1.6 ]
Number of long_calcul per second: 13.48
❯ PYTHON_JIT=1  ./python/install/bin/python3 loops.py
3.13.2 (main, Feb 26 2025, 23:10:54) [Clang 19.1.6 ]
Number of long_calcul per second: 18.38
```

**Comment by brandtbucher** [comment]
Mind sharing `loops.py`?

**Review by geofft — APPROVED** [review]

**Comment by zanieb** [comment]
@brandtbucher yeah np, just took this from the report asking for the feature as a quick test https://github.com/astral-sh/python-build-standalone/issues/535

```python
import time
import sys


def short_calcul(n):
    result = 0
    for i in range(1, n+1):
        result += i
    return result


def long_calcul(num):
    result = 0
    for i in range(num):
        result += short_calcul(i) - short_calcul(i)
    return result


number = 1000
time_total = 8

for _ in range(10):
    long_calcul(number)

n_test = 10
assert short_calcul(n_test) == n_test * (n_test + 1) // 2
assert long_calcul(number) == 0

t_start = time.perf_counter()
long_calcul(number)
t_1_long_calcul = time.perf_counter() - t_start

number_long_calcul = int(time_total / t_1_long_calcul)


t_start = time.perf_counter()
for _ in range(number_long_calcul):
    long_calcul(number)
t_tot = time.perf_counter() - t_start

print(sys.version)
print(f"Number of long_calcul per second: {number_long_calcul/t_tot:.2f}")
```

Nothing special about it otherwise.

**Comment by harshil21** [comment]
Thanks for this feature! I noticed that this isn't available on arm64 linux. Are there any plans on building with this enabled on that platform?
